const FishEvents = {
  SPAWN_FISH: 'SPAWN_FISH',
  FISH_INITIALIZE: 'FISH_INITIALIZE',
  USER_CONNECTED: 'USER_CONNECTED',
  FISH_SPAWNED: 'FISH_SPAWNED',
  FISH_UPDATED: 'FISH_UPDATED',
  FISH_DELETED: 'FISH_DELETED'
}

export { FishEvents };